name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository without submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

           # Setup Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'      # Specify the desired Ruby version
          bundler-cache: true      # Enable bundler caching for faster builds

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Upload build artifacts for Pages
      - name: Upload site to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site


  deploy:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
